locale = ru_RU
directory.default = /
directory.last.left = C:\\
directory.last.right = C:\\
# i use settings for my own machine. Users have to change values according to utils that they use
# TODO make the ability to change these values in program
linux.console = foot -D
linux.open_command = xdg-open
linux.move_to_trash_command = gio trash 