locale = ru_RU
last.directory.left = C:\\
last.directory.right = C:\\
default.directory.linux = /
default.directory.windows = C:\\
# i use settings for my own machine. Users have to change values according to utils that they use
# TODO make the ability to change these values in program
linux.console = konsole --workdir=%s
linux.open_command = xdg-open %s